# Generated by Django 5.1.2 on 2024-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(default='', upload_to='game_covers/'),
            preserve_default=False,
        ),
    ]
